trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Deploy ARM Template'
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'newPrueba'
      subscriptionId: 'cc376f3b-7525-4659-afd2-18f7b850cef7'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'NetworkWatcherRG'
      location: 'East US'
      templateLocation: 'Linked artifact'
      csmFile: 'azuredeploy.json'
      csmParametersFile: 'azuredeploy.parameters.json'